[env:ATmega328P]
platform = atmelavr
board = ATmega328P
framework = arduino

board_build.f_cpu = 16000000L
monitor_speed = 9600

;for upload
upload_protocol = custom
upload_flags =
    -C
    $PROJECT_PACKAGES_DIR/tool-avrdude/avrdude.conf
    -p
    atmega328p
    -Pusb
    -c
    xplainedmini
    -e
upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i
; Descarca automat biblioteca pentru ecran
lib_deps = marcoschwartz/LiquidCrystal_I2C@^1.1.4